/**
 * Types mirroring public/data/catalog.json (generated by the Python build —
 * never edited by hand; see AGENTS §5). Fields beyond these are not consumed
 * by the web app yet.
 */

/**
 * Case templates carry author + gallery attribution; framework blueprints
 * point at the upstream framework document instead (author may be empty).
 */
export interface CatalogSource {
  project: string;
  repository: string;
  caseId?: number;
  document?: string;
  author?: string;
  sourceUrl?: string;
  galleryUrl?: string;
  license: string;
}

export interface CatalogTemplate {
  id: string;
  title: string;
  kind: 'case' | 'framework';
  category: string;
  styles: string[];
  scenes: string[];
  tags: string[];
  language: string;
  mode: string;
  blueprintInputMode: 'text-to-image' | 'image-to-image';
  requiresText: boolean;
  preview: string;
  generatedPreview: string | null;
  generatedPromptPath: string | null;
  promptPath: string;
  source: CatalogSource | null;
  promptSha256: string;
}

export interface CatalogStats {
  total: number;
  cases: number;
  frameworks: number;
}

export interface CatalogFilters {
  categories: string[];
  modes: string[];
  blueprintInputModes: string[];
  styles: string[];
  scenes: string[];
}

export interface CatalogDocument {
  schemaVersion: string;
  generatedAt: string;
  project: { name: string; nameZh: string; description: string };
  source: { project: string; repository: string; archiveSha256: string; license: string };
  stats: CatalogStats;
  filters: CatalogFilters;
  templates: CatalogTemplate[];
}
